services:
  vpn:
    container_name: media_vpn
    image: qmcgaw/gluetun:latest
    networks:
      - mediastack
    cap_add:
      - NET_ADMIN
    volumes:
      - ${CONFIGROOT}/vpn:/gluetun
    ports:
      - 1080:1080
      - 6883:6883
      - 6883:6883/udp
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_KEY}
      - SERVER_COUNTRIES=Canada
      - SERVER_CITIES=Vancouver
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- -nv --retry-connrefused --post-data "json={\"listen_port\":{{PORT}},\"current_network_interface\":\"{{VPN_INTERFACE}}\",\"random_port\":false,\"upnp\":false}" http://vpn:1080/api/v2/app/setPreferences'
      - VPN_PORT_FORWARDING_DOWN_COMMAND=/bin/sh -c 'wget -O- -nv --retry-connrefused --post-data "json={\"listen_port\":0,\"current_network_interface\":\"lo\"}" http:/vpn:1080/api/v2/app/setPreferences'

  qbittorrent:
    container_name: media_qbittorrent
    depends_on:
      - vpn
    image: linuxserver/qbittorrent:latest
    restart: unless-stopped
    network_mode: service:vpn
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBUI_PORT=1080
    volumes:
      - ${CONFIGROOT}/qbittorrent:/config
      - ${DATAROOT}/torrents:/data/torrents

  plex-server:
    container_name: media_plex-server
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    networks:
      - mediastack
    ports:
      - 32400:32400
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - VERSION=docker
    volumes:
      - ${CONFIGROOT}/plex/db:/config
      - ${CONFIGROOT}/plex/transcode:/transcode
      - ${DATAROOT}/media:/data/media

networks:
  mediastack:
