services:
  vpn:
    container_name: media_vpn
    image: qmcgaw/gluetun:latest
    networks:
      - mediastack
    cap_add:
      - NET_ADMIN
    volumes:
      - ${CONFIGROOT}/vpn:/gluetun
    ports:
      - 1080:1080
      - 6881:6881
      - 6881:6881/udp
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESS}
      - SERVER_CITIES=${SERVER_CITIES}

  qbittorrent:
    container_name: media_qbittorrent
    depends_on:
      - vpn
    image: linuxserver/qbittorrent:latest
    restart: unless-stopped
    network_mode: service:vpn
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBUI_PORT=1080
    volumes:
      - ${CONFIGROOT}/qbittorrent:/config
      - ${DATAROOT}/torrents:/data/torrents

  plex-server:
    container_name: media_plex-server
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    networks:
      - mediastack
    ports:
      - "32400:32400"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - VERSION=docker
    volumes:
      - ${CONFIGROOT}/plex/db:/config
      - ${CONFIGROOT}/plex/transcode:/transcode
      - ${DATAROOT}/media:/data/media

  sonarr:
    container_name: media_sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    networks:
      - mediastack
    ports:
      - "8989:8989"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGROOT}/sonarr:/config
      - ${DATAROOT}:/data

  radarr:
    container_name: media_radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    networks:
      - mediastack
    ports:
      - "7878:7878"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGROOT}/radarr:/config
      - ${DATAROOT}:/data

  prowlarr:
    container_name: media_prowlarr
    image: lscr.io/linuxserver/prowlarr:develop
    restart: unless-stopped
    networks:
      - mediastack
    ports:
      - "9696:9696"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
    volumes:
      - ${CONFIGROOT}/prowlarr:/config

  seerr:
    container_name: media_seerr
    image: sctx/seerr:latest
    init: true
    networks:
      - mediastack
      - wanfacing
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    ports:
      - "5055:5055"
    volumes:
      - ${CONFIGROOT}/overseer:/app/config
    restart: unless-stopped

  reclaimerr:
    container_name: media_reclaimerr
    networks:
      - mediastack
    image: ghcr.io/jessielw/reclaimerr:latest
    restart: unless-stopped
    volumes:
      - ${CONFIGROOT}/reclaimerr:/app/data
    ports:
      - "8249:8000"

  rangarr:
    image: judochinx/rangarr:latest
    container_name: media_rangarr
    hostname: rangarr
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      LOG_LEVEL: INFO
    volumes:
      - ${CONFIGROOT}/rangarr/config.yaml:/app/config/config.yaml:ro
    networks:
      - mediastack

  killarr:
    image: judochinx/killarr:latest
    container_name: media_killarr
    restart: unless-stopped
    volumes:
      # Mount the same config.yaml you use for rangarr (or a dedicated one)
      - ${CONFIGROOT}/rangarr/config.yaml:/app/config/config.yaml:ro
    environment:
      - LOG_LEVEL=INFO
    networks:
      - mediastack

  cinerr:
    image: alexkouzel/cinerr:latest
    container_name: media_cinerr
    ports:
      - "8080:8080"
    volumes:
      - ${DATAROOT}/media:/media:ro
      - ${CONFIGROOT}/cinerr:/data
    restart: unless-stopped
    networks:
      - mediastack

networks:
  mediastack:
  wanfacing:
    external: true
