version: "3"
# a comment
services:
  vpn:
    container_name: media_vpn
    image: qmcgaw/gluetun:latest
    networks:
      - mediastack
    cap_add:
      - NET_ADMIN # required to modify network interfaces
    volumes:
      - ${CONFIGROOT}/config/vpn:/gluetun
    ports:
      - 1080:1080 # qbittorrent webui
      - 6881:6881 # qbittorrent download
      - 6881:6881/udp
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TZ=${TZ} # timezone, defined in .env
      - VPN_SERVICE_PROVIDER=mullvad # mullvad is cheap, private, and uses wireguard (fast)
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESS}
      - SERVER_CITIES=Vancouver

  qbittorrent:
    container_name: media_qbittorrent
    depends_on:
      - vpn
    image: linuxserver/qbittorrent:latest
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    environment:
      - TZ=${TZ} # timezone, defined in .env
      - WEBUI_PORT=1080 # to stop it from conflicting with stuff
    volumes:
      - ${CONFIGROOT}/config/qbittorrent:/config # config files
      - ${DATAROOT}/downloads:/downloads # downloads folder

  prowlarr:
    container_name: media_prowlarr # prowlarr is neat, lets you point sonarr and radarr to it for easy indexers
    image: lscr.io/linuxserver/prowlarr:develop
    restart: unless-stopped
    networks:
      - mediastack
    ports:
      - "9696:9696"
    environment:
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - ${CONFIGROOT}/config/prowlarr:/config

  plex-server:
    container_name: media_plex-server
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    ports:
      - "32400:32400"
    environment:
      - TZ=${TZ} # timezone, defined in .env
      - PLEX_CLAIM=${PLEX_CLAIM}
      - VERSION=docker
    volumes:
      - ${CONFIGROOT}/config/plex/db:/config # plex database
      - ${CONFIGROOT}/config/plex/transcode:/transcode # temp transcoded files
      - ${DATAROOT}/complete/tv:/tv # media library
      - ${DATAROOT}/complete/movies:/movies

  sonarr:
    container_name: media_sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    networks:
      - mediastack
    ports:
      - "8989:8989"
    environment:
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGROOT}/config/sonarr:/config # config files
      - ${DATAROOT}/complete/tv:/tv # tv shows folder
      - ${DATAROOT}/downloads:/downloads # download folder

  radarr:
    container_name: media_radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    ports:
      - "7878:7878"
    networks:
      - mediastack
    environment:
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGROOT}/config/radarr:/config # config files
      - ${DATAROOT}/complete/movies:/movies # movies folder
      - ${DATAROOT}/downloads:/downloads # download folder

  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: media_tautulli
    restart: unless-stopped
    networks:
      - mediastack
    volumes:
      - ${CONFIGROOT}/config/tautulli:/config
    environment:
      - TZ=${TZ}
    ports:
      - "8181:8181"

  overseerr: # this is request.davidhoeppner.ca
    container_name: media_overseerr
    image: sctx/overseerr:latest
    networks:
      - mediastack
      - wanfacing
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
    ports:
      - "5055:5055"
    volumes:
      - ${CONFIGROOT}/config/overseer:/app/config
    restart: unless-stopped

networks:
  mediastack:
  wanfacing:
    external: true
